services:
  # ============================= Infrastructure =============================
  eureka-server:
    build:
      context: ./JM-Eureka
    image: jm/eureka-server
    container_name: jm-infra-eureka
    profiles:
      - "all"
      - "infra"
    ports:
      - "8070:8070"
    environment:
      EUREKA_INSTANCE_HOSTNAME: eureka-server
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail --silent http://localhost:8070/actuator/health/readiness || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - job-manager

  gateway:
    build:
      context: .
      dockerfile: JM-Gateway/Dockerfile
      secrets:
        - GITHUB_USERNAME
        - GITHUB_KEY
    image: jm/gateway-server
    container_name: jm-infra-gateway
    profiles:
      - "all"
    ports:
      - "8072:8072"
    env_file: ./.gateway.env
    environment:
      EUREKA_INSTANCE_HOSTNAME: eureka-server
    depends_on:
      eureka-server:
        condition: service_healthy
      auth-service:
        condition: service_healthy
      profile-service:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
      tag-service:
        condition: service_healthy
      subscription-service:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail --silent http://localhost:8072/actuator/health/readiness || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - job-manager

  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    container_name: jm-infra-kafka
    profiles:
      - "all"
      - "infra"
    ports:
      - "9192:9092"
      - "9193:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      # 1. CONTROLLER: 9093 (Quản lý Cluster)
      # 2. PLAINTEXT: 29092 (Nội bộ Docker - Cho Schema Registry dùng)
      # 3. PLAINTEXT_HOST: 9092 (Bên ngoài - Cho Spring Boot dùng)
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:29092,CONTROLLER://kafka:9093,PLAINTEXT_HOST://0.0.0.0:9092"
      # - Nội bộ: kafka:29092
      # - Bên ngoài: localhost:9092
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9192"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
      CLUSTER_ID: "Mk3OEYBSD34fcwNTJENDW233"
    healthcheck:
      test: [ "CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - kafka_data:/var/lib/kafka/data
    networks:
      - job-manager

  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    hostname: jm-schema-registry
    container_name: jm-infra-schema-registry
    profiles:
      - "all"
      - "infra"
    ports:
      - "9191:9091"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "kafka:29092"
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:9091
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC_CONFIG_CLEANUP_POLICY: "compact"
    depends_on:
      - kafka
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:9091/subjects" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - job-manager

  # ============================= Services =============================
  auth-service:
    build:
      context: .
      dockerfile: JM-CompanyAuthService/Dockerfile
      secrets:
        - GITHUB_USERNAME
        - GITHUB_KEY
      cache_from:
        - jm/company-auth-service:latest
    image: jm/company-auth-service
    container_name: jm-service-auth
    profiles:
      - "all"
    ports:
      - "8180:8080"
    env_file:
      - ./JM-CompanyAuthService/CompanyAuthService/.auth.env
    environment:
      SERVER_PORT: 8080
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8070/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-db:5432/auth_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      REDIS_HOST: redis
      REDIS_PASSWORD:
      REDIS_PORT: 6379
      OAUTH2_CLIENT_ID: ${OAUTH2_CLIENT_ID}
      OAUTH2_CLIENT_SECRET: ${OAUTH2_CLIENT_SECRET}
      KAFKA_HOST_URL: kafka:29092
      SCHEMA_REGISTRY_HOST_URL: http://schema-registry:9091
    depends_on:
      eureka-server:
        condition: service_healthy
      kafka:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
      auth-db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail --silent http://localhost:8080/actuator/health/readiness | grep UP || exit 1",
        ]
      interval: 15s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - job-manager

  profile-service:
    build:
      context: .
      dockerfile: JM-CompanyProfileService/Dockerfile
      secrets:
        - GITHUB_USERNAME
        - GITHUB_KEY
      cache_from:
        - jm/company-profile-service:latest
    image: jm/company-profile-service
    container_name: jm-service-profile
    profiles:
      - "all"
    ports:
      - "8181:8081"
    env_file:
      - ./JM-CompanyProfileService/CompanyProfileService/.profile.env
    environment:
      SERVER_PORT: 8081
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8070/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://profile-db:5432/profile_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      KAFKA_HOST_URL: kafka:29092
      SCHEMA_REGISTRY_HOST_URL: http://schema-registry:9091
    depends_on:
      eureka-server:
        condition: service_healthy
      kafka:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
      profile-db:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail --silent http://localhost:8081/actuator/health/readiness | grep UP || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - job-manager

  discovery-service:
    build:
      context: .
      dockerfile: JM-ApplicantDiscoveryService/Dockerfile
      secrets:
        - GITHUB_USERNAME
        - GITHUB_KEY
      cache_from:
        - jm/company-discovery-service:latest
    image: jm/company-discovery-service
    container_name: jm-service-discovery
    profiles:
      - "all"
    ports:
      - "8182:8082"
    env_file:
      - ./JM-ApplicantDiscoveryService/ApplicantDiscoveryService/.discovery.env
    environment:
      SERVER_PORT: 8082
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8070/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://discovery-db:5432/discovery_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      KAFKA_HOST_URL: kafka:29092
      SCHEMA_REGISTRY_HOST_URL: http://schema-registry:9091
    depends_on:
      eureka-server:
        condition: service_healthy
      kafka:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
      discovery-db:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail --silent http://localhost:8082/actuator/health/readiness | grep UP || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - job-manager

  jobpost-service:
    build:
      context: .
      dockerfile: JM-JobPostService/Dockerfile
      secrets:
        - GITHUB_USERNAME
        - GITHUB_KEY
      cache_from:
        - jm/company-jobpost-service:latest
    image: jm/company-jobpost-service
    container_name: jm-service-jobpost
    profiles:
      - "all"
    ports:
      - "8183:8083"
    env_file:
      - ./JM-JobPostService/JobPostService/.jobpost.env
    environment:
      SERVER_PORT: 8083
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8070/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://jobpost-db:5432/jobpost_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      KAFKA_HOST_URL: kafka:29092
      SCHEMA_REGISTRY_HOST_URL: http://schema-registry:9091
    depends_on:
      eureka-server:
        condition: service_healthy
      kafka:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
      jobpost-db:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail --silent http://localhost:8083/actuator/health/readiness | grep UP || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - job-manager

  media-service:
    build:
      context: .
      dockerfile: JM-CompanyMediaService/Dockerfile
      secrets:
        - GITHUB_USERNAME
        - GITHUB_KEY
      cache_from:
        - jm/company-media-service:latest
    image: jm/company-media-service
    container_name: jm-service-media
    profiles:
      - "all"
    ports:
      - "8184:8084"
    env_file:
      - ./JM-CompanyMediaService/CompanyMediaService/.media.env
    environment:
      SERVER_PORT: 8084
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8070/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://media-db:5432/media_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      KAFKA_HOST_URL: kafka:29092
      SCHEMA_REGISTRY_HOST_URL: http://schema-registry:9091
    depends_on:
      eureka-server:
        condition: service_healthy
      kafka:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
      media-db:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail --silent http://localhost:8084/actuator/health/readiness | grep UP || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - job-manager

  tag-service:
    build:
      context: .
      dockerfile: JM-SkillTagService/Dockerfile
      secrets:
        - GITHUB_USERNAME
        - GITHUB_KEY
      cache_from:
        - jm/company-tag-service:latest
    image: jm/company-tag-service
    container_name: jm-service-tag
    profiles:
      - "all"
    ports:
      - "8185:8085"
    env_file:
      - ./JM-SkillTagService/SkillTagService/.tag.env
    environment:
      SERVER_PORT: 8085
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8070/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://tag-db:5432/tag_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      KAFKA_HOST_URL: kafka:29092
      SCHEMA_REGISTRY_HOST_URL: http://schema-registry:9091
    depends_on:
      eureka-server:
        condition: service_healthy
      kafka:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
      tag-db:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail --silent http://localhost:8085/actuator/health/readiness | grep UP || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - job-manager

  subscription-service:
    build:
      context: .
      dockerfile: JM-CompanySubscriptionService/Dockerfile
      secrets:
        - GITHUB_USERNAME
        - GITHUB_KEY
      cache_from:
        - jm/company-subscription-service:latest
    image: jm/company-subscription-service
    container_name: jm-service-subscription
    profiles:
      - "all"
    ports:
      - "8186:8086"
    env_file:
      - ./JM-CompanySubscriptionService/CompanySubscriptionService/.subscription.env
    environment:
      SERVER_PORT: 8086
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8070/eureka/
      SPRING_DATASOURCE_URL: jdbc:postgresql://subscription-db:5432/subscription_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      KAFKA_HOST_URL: kafka:29092
      SCHEMA_REGISTRY_HOST_URL: http://schema-registry:9091
    depends_on:
      eureka-server:
        condition: service_healthy
      kafka:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
      subscription-db:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail --silent http://localhost:8086/actuator/health/readiness | grep UP || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - job-manager

  # ============================= Databases =============================
  auth-db:
    image: postgres:latest
    container_name: jm-db-auth
    profiles:
      - "all"
      - "infra"
      - "dbs"
    ports:
      - "5532:5432"
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d auth_db || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - job-manager

  profile-db:
    image: postgres:latest
    container_name: jm-db-profile
    profiles:
      - "all"
      - "infra"
      - "dbs"
    ports:
      - "5533:5432"
    environment:
      POSTGRES_DB: profile_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d profile_db || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - job-manager

  discovery-db:
    image: postgres:latest
    container_name: jm-db-discovery
    profiles:
      - "all"
      - "infra"
      - "dbs"
    ports:
      - "5534:5432"
    environment:
      POSTGRES_DB: discovery_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d discovery_db || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - job-manager

  jobpost-db:
    image: postgres:latest
    container_name: jm-db-jobpost
    profiles:
      - "all"
      - "infra"
      - "dbs"
    ports:
      - "5535:5432"
    environment:
      POSTGRES_DB: jobpost_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d jobpost_db || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - job-manager

  media-db:
    image: postgres:latest
    container_name: jm-db-media
    profiles:
      - "all"
      - "infra"
      - "dbs"
    ports:
      - "5536:5432"
    environment:
      POSTGRES_DB: media_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d media_db || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - job-manager

  tag-db:
    image: postgres:latest
    container_name: jm-db-tag
    profiles:
      - "all"
      - "infra"
      - "dbs"
    ports:
      - "5537:5432"
    environment:
      POSTGRES_DB: tag_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d tag_db || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - job-manager

  subscription-db:
    image: postgres:latest
    container_name: jm-db-subscription
    profiles:
      - "all"
      - "infra"
      - "dbs"
    ports:
      - "5538:5432"
    environment:
      POSTGRES_DB: subscription_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d subscription_db || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - job-manager

  # ============================= REDIS =============================
  redis:
    image: redis:7-alpine
    container_name: jm-db-auth-redis
    profiles:
      - "all"
      - "infra"
      - "dbs"
    ports:
      - "6479:6379"
    command: redis-server --appendonly yes
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - job-manager

secrets:
  GITHUB_USERNAME:
    environment: GITHUB_USERNAME
  GITHUB_KEY:
    environment: GITHUB_KEY

volumes:
  kafka_data:

networks:
  job-manager:
    driver: bridge
