include:
  - docker-jm-dbs.yml
  - docker-jm-services.yml

services:
  # ============================= Infrastructure =============================
  eureka-server:
    build:
      context: ./JM-Eureka
    image: jm/eureka-server
    container_name: jm-infra-eureka
    profiles:
      - "all"
      - "infra"
    ports:
      - "8070:8070"
    environment:
      EUREKA_INSTANCE_HOSTNAME: eureka-server
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail --silent http://localhost:8070/actuator/health/readiness || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - job-manager

  gateway-server:
    build:
      context: .
      dockerfile: JM-Gateway/Dockerfile
      secrets:
        - GITHUB_USERNAME
        - GITHUB_KEY
    image: jm/gateway-server
    container_name: jm-infra-gateway
    profiles:
      - "all"
    ports:
      - "8072:8072"
    env_file:
      - ./.env
    environment:
      EUREKA_INSTANCE_HOSTNAME: eureka-server
    depends_on:
      eureka-server:
        condition: service_healthy
      auth-service:
        condition: service_healthy
      profile-service:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
      jobpost-service:
        condition: service_healthy
      media-service:
        condition: service_healthy
      tag-service:
        condition: service_healthy
      subscription-service:
        condition: service_healthy
      payment-service:
        condition: service_healthy
      notification-service:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail --silent http://localhost:8072/actuator/health/readiness || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - job-manager

  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    container_name: jm-infra-kafka
    profiles:
      - "all"
      - "infra"
    ports:
      - "9192:9092"
      - "9193:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      # 1. CONTROLLER: 9093 (Quản lý Cluster)
      # 2. PLAINTEXT: 29092 (Nội bộ Docker - Cho Schema Registry dùng)
      # 3. PLAINTEXT_HOST: 9092 (Bên ngoài - Cho Spring Boot dùng)
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:29092,CONTROLLER://kafka:9093,PLAINTEXT_HOST://0.0.0.0:9092"
      # - Nội bộ: kafka:29092
      # - Bên ngoài: localhost:9092
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9192"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
      CLUSTER_ID: "Mk3OEYBSD34fcwNTJENDW233"
    healthcheck:
      test: [ "CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - kafka_data:/var/lib/kafka/data
    networks:
      - job-manager
#
  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: jm-infra-kafka-ui
    profiles:
      - "all"
      - "infra"
    ports:
      - "9000:8080"
    restart: always
    environment:
      KAFKA_CLUSTERS_0_NAME: "kraft-cluster"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
    depends_on:
      kafka:
        condition: service_healthy
    networks:
      - job-manager

  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    hostname: jm-schema-registry
    container_name: jm-infra-schema-registry
    profiles:
      - "all"
      - "infra"
    ports:
      - "9191:9091"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "kafka:29092"
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:9091
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC_CONFIG_CLEANUP_POLICY: "compact"
    depends_on:
      kafka:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:9091/subjects" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - job-manager

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.0
    container_name: jm-infra-elastic-search
    ports:
      - "9201:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s
    restart: unless-stopped
    networks:
      - job-manager

    # Kibana for Elasticsearch Visualization
  kibana:
    image: docker.elastic.co/kibana/kibana:9.0.0
    container_name: jm-infra-kibana-search
    ports:
      - "5602:5602"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9201
      - SERVER_NAME=kibana
      - SERVER_HOST=0.0.0.0
    depends_on:
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:5602/api/status || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s
    restart: unless-stopped
    networks:
      - job-manager

secrets:
  GITHUB_USERNAME:
    environment: GITHUB_USERNAME
  GITHUB_KEY:
    environment: GITHUB_KEY

volumes:
  kafka_data:
  elasticsearch-data:

networks:
  job-manager:
    driver: bridge
