services:
  # ============================= Infrastructure =============================
  eureka-server:
    build:
      context: ./JM-Eureka
    image: jm/eureka-server
    container_name: company-eureka-server
    ports:
      - "8070:8070"
    environment:
      EUREKA_INSTANCE_HOSTNAME: eureka-server
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail --silent http://localhost:8070/actuator/health/readiness || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - job-manager

  gateway:
    build:
      context: ./JM-Gateway
    image: jm/gateway-server
    container_name: company-gateway-server
    ports:
      - "8072:8072"
    environment:
      EUREKA_INSTANCE_HOSTNAME: eureka-server
    depends_on:
      eureka-server:
        condition: service_healthy
      auth-service:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail --silent http://localhost:8072/actuator/health/readiness || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - job-manager

  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    container_name: company-kafka
    ports:
      - "9192:9092"
      - "9193:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"

      # 1. CONTROLLER: 9093 (Quản lý Cluster)
      # 2. PLAINTEXT: 29092 (Nội bộ Docker - Cho Schema Registry dùng)
      # 3. PLAINTEXT_HOST: 9092 (Bên ngoài - Cho Spring Boot dùng)
      KAFKA_LISTENERS: "PLAINTEXT://kafka:29092,CONTROLLER://kafka:9093,PLAINTEXT_HOST://0.0.0.0:9092"

      # - Nội bộ: kafka:29092
      # - Bên ngoài: localhost:9092
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092"

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LOG_DIRS: "/tmp/kraft-combined-logs"
      CLUSTER_ID: "Mk3OEYBSD34fcwNTJENDW233"
    healthcheck: # Kiểm tra Kafka sống chưa trước khi bật Schema Registry
      test: nc -z localhost 9092 || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - kafka_data:/var/lib/kafka/data # Store Kafka logs on your local machine.
    networks:
      - job-manager

  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    hostname: jm-schema-registry
    container_name: jm-schema-registry
    ports:
      - "9191:9091"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "kafka:29092"
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:9091
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC_CONFIG_CLEANUP_POLICY: "compact"
    depends_on:
      - kafka
    restart: on-failure
    networks:
      - job-manager

  # ============================= Services =============================
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
        - GITHUB_USERNAME
        - GITHUB_KEY
    image: jm/company-auth-service
    command: ["java", "-jar", "/app/auth-service.jar"]
    container_name: company-auth-service
    ports:
      - "8180:8080"
    env_file:
      - ./JM-CompanyAuthService/CompanyAuthService/.auth.env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-db:5432/auth_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8070/eureka/
      REDIS_HOST: redis
      REDIS_PASSWORD:
      JWE_PUBLIC_KEY_PATH: classpath:keys/public_key.pem
      JWE_PRIVATE_KEY_PATH: classpath:keys/private_key.pem
      OAUTH2_CLIENT_ID: ${OAUTH2_CLIENT_ID}
      OAUTH2_CLIENT_SECRET: ${OAUTH2_CLIENT_SECRET}
    depends_on:
      eureka-server:
        condition: service_healthy
      auth-db:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail --silent http://localhost:8080/actuator/health/readiness | grep UP || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - job-manager

  profile-service:
    build:
      context: .
      dockerfile: Dockerfile
      secrets:
        - GITHUB_USERNAME
        - GITHUB_KEY
    image: jm/company-profile-service
    command: ["java", "-jar", "/app/profile-service.jar"]
    container_name: company-profile-service
    ports:
      - "8181:8081"
    env_file:
      - ./JM-CompanyProfileService/CompanyProfileService/.profile.env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://profile-db:5432/profile_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8070/eureka/
    depends_on:
      eureka-server:
        condition: service_healthy
      profile-db:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail --silent http://localhost:8081/actuator/health/readiness | grep UP || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - job-manager

  # ============================= Databases =============================
  auth-db:
    image: postgres:latest
    container_name: company-auth-db
    ports:
      - "5533:5432"
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d auth_db || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - job-manager

  profile-db:
    image: postgres:latest
    container_name: company-profile-db
    ports:
      - "5534:5432"
    environment:
      POSTGRES_DB: profile_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d profile_db || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - job-manager

  discovery-db:
    image: postgres:latest
    container_name: company-discovery-db
    ports:
      - "5535:5432"
    environment:
      POSTGRES_DB: discovery_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d discovery_db || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - job-manager

  # ============================= REDIS =============================
  redis:
    image: redis:7-alpine
    container_name: company-auth-redis
    ports:
      - "6479:6379"
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - job-manager

secrets:
  GITHUB_USERNAME:
    environment: GITHUB_USERNAME
  GITHUB_KEY:
    environment: GITHUB_KEY

volumes:
  kafka_data:

networks:
  job-manager:
    driver: bridge
